import type { NextPage } from "next";
import Head from "next/head";
import Typography from "@mui/material/Typography";
import React from "react";
import { Box } from "@mui/system";
import Link from "@mui/material/Link";
import KeyboardArrowRightRoundedIcon from "@mui/icons-material/KeyboardArrowRightRounded";

type Props = {
  isDesktop: boolean;
};

const Home: NextPage<Props> = ({ isDesktop }) => {
  return (
    <>
      <Head>
        <title>Buy & Sell</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box
        sx={{
          overflow: "hidden",
          minHeight: "100vh",
        }}
      >
        <Box
          sx={{
            float: "right",
            width: isDesktop ? "85%" : "100%",
            position: "relative",
            paddingTop: "9.5vh",
            paddingRight: isDesktop ? "25%" : undefined,
            "&::before": {
              content: '""',
              zIndex: -1,
              transform: "rotate(-2.44deg)",
              transformOrigin: "top right",
              backgroundColor: "secondary.main",
              borderRadius: "0 0 0 30px",
              position: "absolute",
              right: 0,
              top: 0,
              width: isDesktop ? "103%" : "140%",
              height: "100%",
              marginLeft: !isDesktop ? undefined : "-40%",
            },
          }}
        >
          <Box
            sx={{
              display: "grid",
              gridTemplateColumns: isDesktop ? "50% 50%" : "100%",
              gridTemplateRows: isDesktop ? "50% 50%" : "25% 50% 25%",
              gridTemplateAreas: isDesktop
                ? `"header form""paragraph form"`
                : `"header""form""paragraph"`,
              columnGap: "18%",
              width: "100%",
              minHeight: "50vh",
              paddingTop: "10%",
              paddingLeft: "10%",
              paddingRight: "10%",
              paddingBottom: isDesktop ? undefined : "10%",
            }}
          >
            <Typography
              variant="h1"
              color="secondary.contrastText"
              sx={{ gridArea: "header", fontSize: isDesktop ? "4rem" : "2rem" }}
              mb={5}
            >
              <Typography
                variant="h1"
                component="span"
                color="primary.main"
                sx={{
                  fontSize: isDesktop ? "4rem" : "2rem",
                }}
              >
                {"Buy Bitcoin, "}
              </Typography>
              {"Ethereum, Litecoin and other crypto "}
              <Typography
                variant="h1"
                component="span"
                color="primary.main"
                sx={{
                  fontSize: isDesktop ? "4rem" : "2rem",
                }}
              >
                online
              </Typography>
            </Typography>
            <Box sx={{ gridArea: "paragraph" }}>
              <Typography
                variant="body1"
                color="secondary.contrastText"
                gutterBottom
                sx={{
                  gridArea: "paragraph",
                  fontSize: isDesktop ? "1.5rem" : "1.2rem",
                }}
                mb={3}
              >
                Why bother going through complicated exchanges? Buy
                cryptocurrency with top payment methods like SEPA bank transfer,
                Credit and Debit Card, Apple Pay, Mobile balance or Klarna. You
                can buy Bitcoin, Ethereum or any other popular crypto directly
                to your personal wallet without making any initial deposits.
                It&apos;s as easy as it gets!
              </Typography>
              {isDesktop && (
                <Link
                  href="https://dashboard.coingate.com/register"
                  underline="hover"
                  sx={{
                    fontSize: "1.25rem",
                    display: "flex",
                    alignItems: "center",
                  }}
                >
                  Start now <KeyboardArrowRightRoundedIcon />
                </Link>
              )}
            </Box>
            <Box
              sx={{
                backgroundColor: "background.paper",
                borderRadius: "30px",
                width: isDesktop ? "75%" : "100%",
                height: "40vh", //TODO: delete me
                gridArea: "form",
                position: "relative",
                marginBottom: isDesktop ? undefined : "10%",
                "&::before": isDesktop
                  ? {
                      position: "absolute",
                      width: "100%",
                      height: "100%",
                      content: '""',
                      zIndex: -1,
                      backgroundColor: "#E9F6FF",
                      top: "-10%",
                      left: "-13%",
                      transform: "rotate(-5.53deg)",
                      borderRadius: "30px",
                    }
                  : undefined,
              }}
            />
          </Box>
        </Box>
      </Box>
    </>
  );
};

export default Home;
