import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Box } from "@mui/system";
import { Header } from "../components/Header";
import { Description } from "../components/Description";
import { Form } from "../components/Form";

type Props = {
  isDesktop: boolean;
};
const Home: NextPage<Props> = ({ isDesktop }) => {
  const [rates, setRates] = useState<Record<
    string,
    Record<string, string>
  > | null>(null);

  useEffect(() => {
    async function fetchRates() {
      // const response = await fetch("https://api.coingate.com/v2/rates");
      // const rates = await response.json();
      const rates = {
        BTC: { EUR: "54741.1" },
        LTC: { EUR: "178.91" },
        ETH: { EUR: "3978.72" },
        BCH: { EUR: "533.0" },
        XRP: { EUR: "1.04" },
        NANO: { EUR: "5.35" },
        TRX: { EUR: "0.0934" },
        DAI: { EUR: "0.8638" },
        ETC: { EUR: "48.57" },
        DOGE: { EUR: "0.2378" },
        XLM: { EUR: "0.3391" },
        BNB: { EUR: "479.0" },
        LINK: { EUR: "27.8" },
        AVA: { EUR: "2.58" },
        VET: { EUR: "0.12" },
        BTCV: { EUR: "6.84" },
        DOT: { EUR: "44.89" },
        MATIC: { EUR: "1.8" },
        ADA: { EUR: "1.84" },
        UNI: { EUR: "23.09" },
        BUSD: { EUR: "0.8641" },
        SOL: { EUR: "202.65" },
        WBTC: { EUR: "54766.1" },
        THETA: { EUR: "6.49" },
        ICP: { EUR: "41.41" },
      };
      setRates(rates);
    }
    fetchRates();
  }, []);

  return (
    <>
      <Head>
        <title>Buy & Sell</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box
        component="main"
        sx={{
          overflow: "hidden",
          minHeight: "100vh",
        }}
      >
        <Box
          sx={{
            float: "right",
            width: isDesktop ? "85%" : "100%",
            position: "relative",
            paddingTop: "9.5vh",
            paddingRight: isDesktop ? "25%" : undefined,
            "&::before": {
              content: '""',
              zIndex: -1,
              transform: "rotate(-2.44deg)",
              transformOrigin: "top right",
              backgroundColor: "secondary.main",
              borderRadius: "0 0 0 30px",
              position: "absolute",
              right: 0,
              top: 0,
              width: isDesktop ? "103%" : "140%",
              height: "100%",
              marginLeft: !isDesktop ? undefined : "-40%",
            },
          }}
        >
          <Box
            sx={{
              display: "grid",
              gridTemplateColumns: isDesktop ? "50% 50%" : "100%",
              gridTemplateRows: isDesktop ? "50% 50%" : "25% 50% 25%",
              gridTemplateAreas: isDesktop
                ? `"header form""paragraph form"`
                : `"header""form""paragraph"`,
              columnGap: "18%",
              width: "100%",
              minHeight: "50vh",
              paddingTop: "10%",
              paddingLeft: "10%",
              paddingRight: "10%",
              paddingBottom: isDesktop ? undefined : "10%",
            }}
          >
            <Header isDesktop={isDesktop} />
            <Description isDesktop={isDesktop} />
            <Form isDesktop={isDesktop} rates={rates} />
          </Box>
        </Box>
      </Box>
    </>
  );
};

export default Home;
