import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Box } from "@mui/system";
import { Header } from "../components/Header";
import { Description } from "../components/Description";
import { Form } from "../components/Form";

type Props = {
  isDesktop: boolean;
};
const Home: NextPage<Props> = ({ isDesktop }) => {
  const [rates, setRates] = useState<Record<
    string,
    Record<string, string>
  > | null>(null);

  useEffect(() => {
    async function fetchRates() {
      const response = await fetch("/api/rates");
      const rates = await response.json();
      setRates(rates);
    }
    fetchRates();
  }, []);

  return (
    <>
      <Head>
        <title>Buy & Sell</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box
        component="main"
        sx={{
          overflow: "auto",
          minHeight: "100vh",
        }}
      >
        <Box
          sx={{
            float: "right",
            width: isDesktop ? "85%" : "100%",
            position: "relative",
            paddingTop: "9.5vh",
            paddingRight: isDesktop ? "25%" : undefined,
            "&::before": {
              content: '""',
              zIndex: -1,
              transform: "rotate(-2.44deg)",
              transformOrigin: "top right",
              backgroundColor: "secondary.main",
              borderRadius: "0 0 0 30px",
              position: "absolute",
              right: 0,
              top: 0,
              width: isDesktop ? "103%" : "140%",
              height: "100%",
              marginLeft: !isDesktop ? undefined : "-40%",
            },
          }}
        >
          <Box
            sx={{
              display: "grid",
              gridTemplateColumns: isDesktop ? "50% 50%" : "100%",
              gridTemplateRows: isDesktop ? "50% 50%" : "25% 50% 25%",
              gridTemplateAreas: isDesktop
                ? `"header form""paragraph form"`
                : `"header""form""paragraph"`,
              columnGap: "18%",
              width: "100%",
              minHeight: "50vh",
              paddingTop: "10%",
              paddingLeft: "10%",
              paddingRight: "10%",
              paddingBottom: isDesktop ? undefined : "10%",
            }}
          >
            <Header isDesktop={isDesktop} />
            <Description isDesktop={isDesktop} />

            <Form isDesktop={isDesktop} rates={rates} />
          </Box>
        </Box>
      </Box>
    </>
  );
};

export default Home;
